import {
  PortfolioSummary,
  Position,
  StockQuote,
  AgentDecision,
  TradeRecord,
  AgentActivityEvent,
  RiskRuleConfig,
} from "../types/index.js";

class MockDataStore {
  public portfolio: PortfolioSummary = {
    equity: 104850.25,
    cash: 42120.8,
    buyingPower: 84241.6,
    dailyPL: 1420.5,
    dailyPLPercent: 1.37,
    totalPL: 4850.25,
    totalPLPercent: 4.85,
    portfolioHistory: [
      { time: "09:30", value: 103429.75 },
      { time: "10:00", value: 103850.0 },
      { time: "10:30", value: 103600.25 },
      { time: "11:00", value: 104100.0 },
      { time: "11:30", value: 103950.5 },
      { time: "12:00", value: 104250.0 },
      { time: "12:30", value: 104400.75 },
      { time: "13:00", value: 104150.0 },
      { time: "13:30", value: 104500.25 },
      { time: "14:00", value: 104650.0 },
      { time: "14:30", value: 104350.5 },
      { time: "15:00", value: 104720.0 },
      { time: "15:30", value: 104850.25 },
    ],
  };

  public positions: Position[] = [
    {
      symbol: "AAPL",
      name: "Apple Inc.",
      shares: 40,
      avgEntryPrice: 218.4,
      currentPrice: 228.65,
      marketValue: 9146.0,
      unrealizedPL: 410.0,
      unrealizedPLPercent: 4.69,
      allocationPercent: 8.72,
      side: "long",
    },
    {
      symbol: "NVDA",
      name: "NVIDIA Corporation",
      shares: 65,
      avgEntryPrice: 118.2,
      currentPrice: 128.9,
      marketValue: 8378.5,
      unrealizedPL: 695.5,
      unrealizedPLPercent: 9.05,
      allocationPercent: 7.99,
      side: "long",
    },
    {
      symbol: "MSFT",
      name: "Microsoft Corp.",
      shares: 20,
      avgEntryPrice: 432.1,
      currentPrice: 448.25,
      marketValue: 8965.0,
      unrealizedPL: 323.0,
      unrealizedPLPercent: 3.74,
      allocationPercent: 8.55,
      side: "long",
    },
    {
      symbol: "AMZN",
      name: "Amazon.com Inc.",
      shares: 35,
      avgEntryPrice: 182.5,
      currentPrice: 188.7,
      marketValue: 6604.5,
      unrealizedPL: 217.0,
      unrealizedPLPercent: 3.4,
      allocationPercent: 6.3,
      side: "long",
    },
    {
      symbol: "SPY",
      name: "SPDR S&P 500 ETF Trust",
      shares: 50,
      avgEntryPrice: 542.0,
      currentPrice: 552.75,
      marketValue: 27637.5,
      unrealizedPL: 537.5,
      unrealizedPLPercent: 1.98,
      allocationPercent: 26.36,
      side: "long",
    },
  ];

  public stocks: StockQuote[] = [
    {
      symbol: "AAPL",
      name: "Apple Inc.",
      price: 228.65,
      change: 2.45,
      changePercent: 1.08,
      volume: "48.2M",
      high: 229.4,
      low: 226.1,
      open: 226.5,
      previousClose: 226.2,
      peRatio: 34.2,
      marketCap: "3.51T",
      sector: "Technology",
      chartData: [
        { time: "09:30", price: 226.5 },
        { time: "11:00", price: 227.1 },
        { time: "12:30", price: 226.8 },
        { time: "14:00", price: 228.2 },
        { time: "15:30", price: 228.65 },
      ],
    },
    {
      symbol: "NVDA",
      name: "NVIDIA Corporation",
      price: 128.9,
      change: 4.15,
      changePercent: 3.33,
      volume: "65.4M",
      high: 130.2,
      low: 125.4,
      open: 125.8,
      previousClose: 124.75,
      peRatio: 68.5,
      marketCap: "3.16T",
      sector: "Semiconductors",
      chartData: [
        { time: "09:30", price: 125.8 },
        { time: "11:00", price: 127.4 },
        { time: "12:30", price: 126.9 },
        { time: "14:00", price: 128.5 },
        { time: "15:30", price: 128.9 },
      ],
    },
    {
      symbol: "MSFT",
      name: "Microsoft Corp.",
      price: 448.25,
      change: 3.1,
      changePercent: 0.7,
      volume: "18.7M",
      high: 449.8,
      low: 445.5,
      open: 446.0,
      previousClose: 445.15,
      peRatio: 36.8,
      marketCap: "3.33T",
      sector: "Software",
      chartData: [
        { time: "09:30", price: 446.0 },
        { time: "11:00", price: 447.2 },
        { time: "12:30", price: 446.8 },
        { time: "14:00", price: 447.9 },
        { time: "15:30", price: 448.25 },
      ],
    },
    {
      symbol: "TSLA",
      name: "Tesla Inc.",
      price: 242.8,
      change: -5.4,
      changePercent: -2.18,
      volume: "38.9M",
      high: 251.2,
      low: 241.5,
      open: 248.5,
      previousClose: 248.2,
      peRatio: 62.1,
      marketCap: "774.2B",
      sector: "Automotive / EV",
      chartData: [
        { time: "09:30", price: 248.5 },
        { time: "11:00", price: 245.8 },
        { time: "12:30", price: 244.2 },
        { time: "14:00", price: 243.1 },
        { time: "15:30", price: 242.8 },
      ],
    },
    {
      symbol: "GOOGL",
      name: "Alphabet Inc.",
      price: 182.15,
      change: 1.25,
      changePercent: 0.69,
      volume: "22.3M",
      high: 183.4,
      low: 180.9,
      open: 181.2,
      previousClose: 180.9,
      peRatio: 25.4,
      marketCap: "2.28T",
      sector: "Technology",
      chartData: [
        { time: "09:30", price: 181.2 },
        { time: "11:00", price: 181.8 },
        { time: "12:30", price: 182.0 },
        { time: "14:00", price: 181.9 },
        { time: "15:30", price: 182.15 },
      ],
    },
    {
      symbol: "AMZN",
      name: "Amazon.com Inc.",
      price: 188.7,
      change: 1.85,
      changePercent: 0.99,
      volume: "29.1M",
      high: 189.5,
      low: 186.8,
      open: 187.1,
      previousClose: 186.85,
      peRatio: 41.2,
      marketCap: "1.96T",
      sector: "Technology",
      chartData: [
        { time: "09:30", price: 187.1 },
        { time: "11:00", price: 187.8 },
        { time: "12:30", price: 188.1 },
        { time: "14:00", price: 188.4 },
        { time: "15:30", price: 188.7 },
      ],
    },
    {
      symbol: "SPY",
      name: "SPDR S&P 500 ETF Trust",
      price: 552.75,
      change: 3.25,
      changePercent: 0.59,
      volume: "52.4M",
      high: 553.4,
      low: 549.8,
      open: 550.2,
      previousClose: 549.5,
      peRatio: 26.1,
      marketCap: "550B",
      sector: "Index ETF",
      chartData: [
        { time: "09:30", price: 550.2 },
        { time: "11:00", price: 551.4 },
        { time: "12:30", price: 551.9 },
        { time: "14:00", price: 552.3 },
        { time: "15:30", price: 552.75 },
      ],
    },
  ];

  public decisions: AgentDecision[] = [
    {
      id: "dec-scenario-a",
      runId: "run-nvda-101",
      symbol: "NVDA",
      decision: "BUY",
      confidence: 86.0,
      reasoning:
        "Technical momentum breakout supported by heavy institutional volume (+28% vs 20-day avg). RSI at 61 confirms bullish continuation without extreme overbought signals. Strong datacenter Blackwell architecture demand provides solid fundamental momentum.",
      suggestedAllocationPct: 3.5,
      suggestedShares: 25,
      riskAssessment: "LOW",
      marketSummary: {
        trend: "BULLISH",
        volumeAnalysis: "Above average accumulation across institutional blocks",
        keyLevels: { support: 122.5, resistance: 132.0 },
      },
      newsSentiment: {
        score: 0.82,
        headline: "Hyperscalers expand generative AI datacenter capital expenditure targets",
        source: "Bloomberg Technology",
      },
      riskResult: {
        approved: true,
        riskLevel: "LOW",
        reasons: ["All 6 deterministic safety rules passed successfully."],
        checks: [
          { name: "max_position_size", label: "Max Position Exposure", threshold: 10.0, actual: 8.0, passed: true, unit: "%" },
          { name: "max_single_trade", label: "Max Single Trade Size", threshold: 5.0, actual: 3.1, passed: true, unit: "%" },
          { name: "max_daily_loss", label: "Max Daily Drawdown", threshold: 2.0, actual: 0.0, passed: true, unit: "%" },
          { name: "min_ai_confidence", label: "Min AI Confidence", threshold: 70.0, actual: 86.0, passed: true, unit: "%" },
          { name: "max_daily_trades", label: "Max Daily Executions", threshold: 10, actual: 3, passed: true, unit: "trades" },
          { name: "max_sector_exposure", label: "Max Tech Sector Cap", threshold: 40.0, actual: 31.6, passed: true, unit: "%" },
        ],
        evaluatedAt: new Date(Date.now() - 3600000).toISOString(),
      },
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      status: "APPROVED_EXECUTED",
      alpacaOrderId: "alpaca-ord-9921",
    },
    {
      id: "dec-scenario-b",
      runId: "run-tsla-102",
      symbol: "TSLA",
      decision: "BUY",
      confidence: 68.0,
      reasoning:
        "Rebound setup near key support zone of $242.00. However, options volatility surface indicates elevated tail risk, and AI confidence score (68%) fails the minimum 70% threshold required for automated paper execution.",
      suggestedAllocationPct: 6.8,
      suggestedShares: 30,
      riskAssessment: "HIGH",
      marketSummary: {
        trend: "SIDEWAYS",
        volumeAnalysis: "Elevated sell volume following delivery report",
        keyLevels: { support: 241.0, resistance: 254.0 },
      },
      newsSentiment: {
        score: 0.41,
        headline: "EV margin pressure rises amid intensifying overseas competition",
        source: "Reuters Markets",
      },
      riskResult: {
        approved: false,
        riskLevel: "CRITICAL",
        reasons: [
          "VETOED: AI confidence of 68.0% is below the mandatory 70.0% floor.",
          "VETOED: Proposed allocation 6.8% exceeds the 5.0% single-trade limit.",
        ],
        checks: [
          { name: "max_position_size", label: "Max Position Exposure", threshold: 10.0, actual: 6.8, passed: true, unit: "%" },
          { name: "max_single_trade", label: "Max Single Trade Size", threshold: 5.0, actual: 6.8, passed: false, unit: "%" },
          { name: "max_daily_loss", label: "Max Daily Drawdown", threshold: 2.0, actual: 0.0, passed: true, unit: "%" },
          { name: "min_ai_confidence", label: "Min AI Confidence", threshold: 70.0, actual: 68.0, passed: false, unit: "%" },
          { name: "max_daily_trades", label: "Max Daily Executions", threshold: 10, actual: 3, passed: true, unit: "trades" },
          { name: "max_sector_exposure", label: "Max Tech Sector Cap", threshold: 40.0, actual: 31.6, passed: true, unit: "%" },
        ],
        evaluatedAt: new Date(Date.now() - 7200000).toISOString(),
      },
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      status: "BLOCKED_BY_RISK",
    },
  ];

  public trades: TradeRecord[] = [
    {
      id: "tr-001",
      alpacaOrderId: "alpaca-ord-9921",
      symbol: "NVDA",
      side: "BUY",
      shares: 25,
      orderType: "market",
      estimatedPrice: 128.5,
      executedPrice: 128.65,
      status: "filled",
      submittedAt: new Date(Date.now() - 3600000).toISOString(),
      executedAt: new Date(Date.now() - 3595000).toISOString(),
      decisionId: "dec-scenario-a",
    },
    {
      id: "tr-002",
      symbol: "TSLA",
      side: "BUY",
      shares: 30,
      orderType: "market",
      estimatedPrice: 242.8,
      status: "blocked",
      submittedAt: new Date(Date.now() - 7200000).toISOString(),
      decisionId: "dec-scenario-b",
      riskReasons: [
        "AI confidence 68.0% < 70.0% floor",
        "Single trade size 6.8% > 5.0% ceiling",
      ],
    },
    {
      id: "tr-003",
      alpacaOrderId: "alpaca-ord-9844",
      symbol: "AAPL",
      side: "BUY",
      shares: 15,
      orderType: "market",
      estimatedPrice: 224.5,
      executedPrice: 224.6,
      status: "filled",
      submittedAt: new Date(Date.now() - 86400000).toISOString(),
      executedAt: new Date(Date.now() - 86395000).toISOString(),
    },
  ];

  public activities: AgentActivityEvent[] = [
    {
      id: "act-001",
      runId: "run-nvda-101",
      timestamp: new Date(Date.now() - 3590000).toISOString(),
      stage: "COMPLETE",
      title: "Trade Executed on Alpaca Paper",
      message: "Order alpaca-ord-9921 filled: BUY 25 NVDA @ $128.65 ($3,216.25).",
      status: "success",
    },
    {
      id: "act-002",
      runId: "run-nvda-101",
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      stage: "RISK_CHECK",
      title: "Risk Engine Approval",
      message: "All 6 deterministic safety rules passed. Proposed allocation 3.1% < 5.0% limit.",
      status: "success",
    },
    {
      id: "act-003",
      runId: "run-tsla-102",
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      stage: "BLOCKED",
      title: "Risk Engine Veto Interception",
      message: "Blocked proposed BUY 30 TSLA. AI confidence (68%) below 70% threshold.",
      status: "warning",
    },
  ];

  public riskRules: RiskRuleConfig[] = [
    {
      id: "rule-1",
      name: "Max Position Size",
      description: "Maximum portfolio equity allocated to any single asset",
      limit: 10.0,
      currentValue: 8.72,
      unit: "%",
      isViolation: false,
    },
    {
      id: "rule-2",
      name: "Max Single Trade Size",
      description: "Maximum capital committed in a single buy transaction",
      limit: 5.0,
      currentValue: 3.1,
      unit: "%",
      isViolation: false,
    },
    {
      id: "rule-3",
      name: "Daily Loss Circuit Breaker",
      description: "Emergency circuit breaker that freezes trading if portfolio drops",
      limit: 2.0,
      currentValue: 0.0,
      unit: "%",
      isViolation: false,
    },
    {
      id: "rule-4",
      name: "Minimum AI Confidence",
      description: "Mandatory algorithmic conviction floor required for order execution",
      limit: 70.0,
      currentValue: 86.0,
      unit: "%",
      isViolation: false,
    },
    {
      id: "rule-5",
      name: "Max Daily Trades",
      description: "Maximum number of filled trades allowed per market trading session",
      limit: 10,
      currentValue: 3,
      unit: "trades",
      isViolation: false,
    },
    {
      id: "rule-6",
      name: "Max Sector Exposure",
      description: "Maximum capital allocation permissible within a single sector",
      limit: 40.0,
      currentValue: 31.6,
      unit: "%",
      isViolation: false,
    },
  ];

  public resetDemoState(): void {
    this.portfolio = {
      equity: 100000.0,
      cash: 100000.0,
      buyingPower: 200000.0,
      dailyPL: 0.0,
      dailyPLPercent: 0.0,
      totalPL: 0.0,
      totalPLPercent: 0.0,
      portfolioHistory: [
        { time: "09:30", value: 100000.0 },
        { time: "16:00", value: 100000.0 },
      ],
    };
    this.positions = [];
    this.trades = [];
    this.decisions = [];
    this.activities = [];
  }
}

export const store = new MockDataStore();
